In [1]:
!pip install nltk textblob pandas

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import nltk
from textblob import TextBlob
import pandas as pd

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [3]:
data = [
    "I love this product! It is amazing 😊",
    "Worst experience ever. Totally disappointed 😡",
    "It's okay, not great but not bad either.",
    "Absolutely fantastic service!",
    "I hate the new update, it's terrible."
]

df = pd.DataFrame(data, columns=['Text'])
df

                                            Text
0           I love this product! It is amazing 😊
1  Worst experience ever. Totally disappointed 😡
2       It's okay, not great but not bad either.
3                  Absolutely fantastic service!
4          I hate the new update, it's terrible.

In [4]:
def get_sentiment(text):
    analysis = TextBlob(text)
    polarity = analysis.sentiment.polarity

    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df['Sentiment'] = df['Text'].apply(get_sentiment)
df

                                            Text Sentiment
0           I love this product! It is amazing 😊  Positive
1  Worst experience ever. Totally disappointed 😡  Negative
2       It's okay, not great but not bad either.  Positive
3                  Absolutely fantastic service!  Positive
4          I hate the new update, it's terrible.  Negative

In [7]:
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

def pos_tagging(text):
    words = nltk.word_tokenize(text)
    tagged = nltk.pos_tag(words)
    return tagged

df['POS_Tags'] = df['Text'].apply(pos_tagging)
df

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

,Text,Sentiment,POS_Tags
0,I love this product! It is amazing 😊,Positive,"[(I, PRP), (love, VBP), (this, DT), (product, ..."
1,Worst experience ever. Totally disappointed 😡,Negative,"[(Worst, NNP), (experience, NN), (ever, RB), (..."
2,"It's okay, not great but not bad either.",Positive,"[(It, PRP), ('s, VBZ), (okay, JJ), (,, ,), (no..."
3,Absolutely fantastic service!,Positive,"[(Absolutely, RB), (fantastic, JJ), (service, ..."
4,"I hate the new update, it's terrible.",Negative,"[(I, PRP), (hate, VBP), (the, DT), (new, JJ), ..."

In [8]:
print(df)

                                            Text Sentiment  \
0           I love this product! It is amazing 😊  Positive
1  Worst experience ever. Totally disappointed 😡  Negative
2       It's okay, not great but not bad either.  Positive
3                  Absolutely fantastic service!  Positive
4          I hate the new update, it's terrible.  Negative

                                            POS_Tags
0  [(I, PRP), (love, VBP), (this, DT), (product, ...
1  [(Worst, NNP), (experience, NN), (ever, RB), (...
2  [(It, PRP), ('s, VBZ), (okay, JJ), (,, ,), (no...
3  [(Absolutely, RB), (fantastic, JJ), (service, ...
4  [(I, PRP), (hate, VBP), (the, DT), (new, JJ), ...